### PR TITLE
Kaleidoscope selection

### PR DESCRIPTION
**Pull request by tomy204**
Kaleidoscope selection is not completely done (changing tumbler doesn't work)

but i made some important changes regarding the handling of the viewport so it would be preferable to merge those change before i continue to work on the rest

this branch should not get deleted after merge as i'll continue to work on it

### CODE REVIEW

**Review by Maaack — CHANGES_REQUESTED** [review]
Currently, this branch broke functionality for me. I was no longer able to rotate the tumbler in the shadertest scene. Also the main scene didn't seem to load anything, nor did the kaleidoscope selection? I think I need more context.
I will make the changes you suggested to the KaleidoscopeViewer (removing the extra layer of ViewportContainer) in a smaller MR.

**Comment by tomy204** [comment]
OK, i got it

it is normal that the shadertest scene doesn't rotate as i moved the input part to a KaleidoscopeController
the issue on the mainScene was because i forgot to relink the viewport texture to the kaleidoscopeviewport after i renamed it

but after getting the cahnges from main, there was conflict on KaleidoscopeViewport.tscn, i choosed to keep the file from main but it broke what i did, going to fix this one and it should work fine

**Comment by tomy204** [comment]
with commit f70e842d05a470d25e11ea664f277fb56289363f

everything is now working
the main Scene makes use of @Maaack work and all input + music works, in main scene you can press E to bring a blue square (which will be replaced by a screenshot of the pattern to match)

the branch have no conflict as i am writing this comment

**Review by Maaack — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
