### PR TITLE
Shadertest

### PR DESCRIPTION
**Pull request by amythyst221**
-Updates kaleidoscope shader with multiple fixes and toggles
-Adds rendering and first person game proto test
-Adds auto rotate functionality to tumbler

### CODE REVIEW

**Comment by tomy204** [comment]
conflicts ! :(

looking at ShaderTest.tscn it seems the Shadertest version have the latest updates, maybe a new update from main would be usefull ?

the KaleidoscopeViewport.tscn and .gd seems completely outdated, should get updated from main

**Comment by tomy204** [comment]
for me the KaleidoscopeViewport should keep the main version

but for ShaderTest.tscn this branch version should be used

needs confirmation from @Maaack to merge

**Review by tomy204 — APPROVED** [review]
after the update from main, conflict have been solved

**Review by Maaack — APPROVED** [review]
Looks good! Thank you. One bit of feedback would be to reduce the size of the hdr, but it's more important this gets merged in sooner.

**Pull request merged**
